# langgraph_simple_agent.py
# Program demonstrates use of LangGraph for a very simple agent.
# It writes to stdout and asks the user to enter a line of text through stdin.
# It passes the line to the LLM llama-3.2-1B-Instruct, then prints the
# what the LLM returns as text to stdout.
# The LLM should use Cuda if available, if not then if mps is available then use that,
# otherwise use cpu.
# After the LangGraph graph is created but before it executes, the program
# uses the Mermaid library to write a image of the graph to the file lg_graph.png
# The program gets the LLM llama-3.2-1B-Instruct from Hugging Face and wraps
# it for LangChain using HuggingFacePipeline.
# The code is commented in detail so a reader can understand each step.

# Import necessary libraries
import torch
from transformers import AutoModelForCausalLM, AutoTokenizer, pipeline
from langchain_huggingface import HuggingFacePipeline
from langgraph.graph import StateGraph, START, END
from typing import TypedDict

# Determine the best available device for inference
# Priority: CUDA (NVIDIA GPU) > MPS (Apple Silicon) > CPU
def get_device():
    """
    Detect and return the best available compute device.
    Returns 'cuda' for NVIDIA GPUs, 'mps' for Apple Silicon, or 'cpu' as fallback.
    """
    if torch.cuda.is_available():
        print("Using CUDA (NVIDIA GPU) for inference")
        return "cuda"
    elif torch.backends.mps.is_available():
        print("Using MPS (Apple Silicon) for inference")
        return "mps"
    else:
        print("Using CPU for inference")
        return "cpu"

# =============================================================================
# STATE DEFINITION
# =============================================================================
# The state is a TypedDict that flows through all nodes in the graph.
# Each node can read from and write to specific fields in the state.
# LangGraph automatically merges the returned dict from each node into the state.

class AgentState(TypedDict):
    """
    State object that flows through the LangGraph nodes.

    Fields:
    - user_input: The text entered by the user (set by get_user_input node)
    - should_exit: Boolean flag indicating if user wants to quit (set by get_user_input node)
    - llm_response: The response generated by the LLM (set by call_llm node)

    State Flow:
    1. Initial state: all fields empty/default
    2. After get_user_input: user_input and should_exit are populated
    3. After call_llm: llm_response is populated
    4. After print_response: state unchanged (node only reads, doesn't write)

    The graph loops continuously:
        get_user_input -> [conditional] -> call_llm -> print_response -> get_user_input
                              |
                              +-> END (if user wants to quit)
    """
    user_input: str
    should_exit: bool
    skip_llm: bool
    trace_enabled: bool
    llama_response: str
    qwen_response: str

def create_model_llm(model_id: str, device: str):
    """
    Create and configure one HuggingFace model wrapped for LangChain.
    for use with LangChain via HuggingFacePipeline.
    """
    print(f"Loading model: {model_id}")
    print("This may take a moment on first run as the model is downloaded/cached...")

    # Load the tokenizer - converts text to tokens the model understands
    tokenizer = AutoTokenizer.from_pretrained(model_id)

    # Load the model itself with appropriate settings for the device
    model = AutoModelForCausalLM.from_pretrained(
        model_id,
        dtype=torch.float16 if device != "cpu" else torch.float32,
        device_map=device if device == "cuda" else None,
    )

    # Move model to MPS device if using Apple Silicon
    if device == "mps":
        model = model.to(device)

    # Create a text generation pipeline that combines model and tokenizer
    pipe = pipeline(
        "text-generation",
        model=model,
        tokenizer=tokenizer,
        max_new_tokens=256,  # Maximum tokens to generate in response
        do_sample=True,      # Enable sampling for varied responses
        temperature=0.7,     # Controls randomness (lower = more deterministic)
        top_p=0.95,          # Nucleus sampling parameter
        pad_token_id=tokenizer.eos_token_id,  # Suppress pad_token_id warning
    )

    # Wrap the HuggingFace pipeline for use with LangChain
    llm = HuggingFacePipeline(pipeline=pipe)

    print(f"Model loaded successfully: {model_id}")
    return llm

def create_graph(llama_llm, qwen_llm):
    """
    Create the LangGraph state graph with three separate nodes:
    1. get_user_input: Reads input from stdin
    2. fan_out_input: Passes normal input to both model branches
    3. call_llama: Sends input to Llama model
    4. call_qwen: Sends input to Qwen model
    5. print_both_responses: Prints both model responses

    Graph structure with conditional routing and internal loop:
        START -> get_user_input -> [conditional] -> fan_out_input -> call_llama --+
                       ^                 |                             call_qwen ---+-> print_both_responses -> get_user_input
                       |                 +-> END (if user wants to quit)
                       +-> get_user_input (commands/empty input self-loop)

    The graph runs continuously until the user types 'quit', 'exit', or 'q'.
    """

    def trace(state: AgentState, message: str) -> None:
        """Print trace output only when tracing is enabled."""
        if state.get("trace_enabled", False):
            print(f"[TRACE] {message}")

    # =========================================================================
    # NODE 1: get_user_input
    # =========================================================================
    # This node reads a line of text from stdin and updates the state.
    # State changes:
    #   - user_input: Set to the text entered by the user
    #   - should_exit: Set to True if user typed quit/exit/q, False otherwise
    #   - llm_response: Unchanged (not modified by this node)
    def get_user_input(state: AgentState) -> dict:
        """
        Node that prompts the user for input via stdin.

        Reads state: Nothing (fresh input each iteration)
        Updates state:
            - user_input: The raw text entered by the user
            - should_exit: True if user wants to quit, False otherwise
        """
        trace(
            state,
            "node=get_user_input entered "
            f"(should_exit={state.get('should_exit')}, skip_llm={state.get('skip_llm')})",
        )

        # Display banner before each prompt
        print("\n" + "=" * 50)
        print("Enter your text ('verbose'/'quiet' to toggle tracing, or 'quit' to exit):")
        print("=" * 50)

        print("\n> ", end="")
        user_input = input()
        normalized = user_input.strip().lower()

        # Check if user wants to exit
        if normalized in ['quit', 'exit', 'q']:
            print("Goodbye!")
            return {
                "user_input": user_input,
                "should_exit": True,        # Signal to exit the graph
                "skip_llm": True,
            }

        # Toggle tracing on
        if normalized == "verbose":
            print("Tracing enabled.")
            return {
                "user_input": user_input,
                "should_exit": False,
                "skip_llm": True,           # Skip model call for command input
                "trace_enabled": True
            }

        # Toggle tracing off
        if normalized == "quiet":
            print("Tracing disabled.")
            return {
                "user_input": user_input,
                "should_exit": False,
                "skip_llm": True,           # Skip model call for command input
                "trace_enabled": False
            }

        # Empty input should reprompt through the graph (self-loop),
        # never reaching call_llm.
        if normalized == "":
            print("Empty input ignored. Please enter some text.")
            return {
                "user_input": user_input,
                "should_exit": False,
                "skip_llm": True
            }

        # Non-empty input - continue to LLM
        return {
            "user_input": user_input,
            "should_exit": False,          # Signal to proceed to LLM
            "skip_llm": False
        }

    # =========================================================================
    # NODE 2: fan_out_input
    # =========================================================================
    # This node exists to make the branching explicit: one node receives user
    # input and then fans out to both model calls in parallel.
    def fan_out_input(state: AgentState) -> dict:
        trace(state, f"node=fan_out_input entered (input={state['user_input']!r})")
        return {}

    # =========================================================================
    # NODE 3: call_llama
    # =========================================================================
    # This node takes the user input from state, sends it to Llama,
    # and stores the response back in state.
    # State changes:
    #   - user_input: Unchanged (read only)
    #   - llama_response: Set to Llama's generated response
    def call_llama(state: AgentState) -> dict:
        """
        Node that invokes the Llama model with the user's input.

        Reads state:
            - user_input: The text to send to the model
        Updates state:
            - llama_response: The text generated by Llama
        """
        trace(state, f"node=call_llama entered (input={state['user_input']!r})")
        user_input = state["user_input"]

        # Format the prompt for the instruction-tuned model
        prompt = f"User: {user_input}\nAssistant:"

        print("\nRunning Llama...")

        # Invoke Llama and get the response
        response = llama_llm.invoke(prompt)
        trace(state, f"node=call_llama completed (response_len={len(response)})")

        # Return only the field we're updating
        return {"llama_response": response}

    # =========================================================================
    # NODE 4: call_qwen
    # =========================================================================
    # This node takes the user input from state, sends it to Qwen,
    # and stores the response back in state.
    def call_qwen(state: AgentState) -> dict:
        trace(state, f"node=call_qwen entered (input={state['user_input']!r})")
        user_input = state["user_input"]
        prompt = f"User: {user_input}\nAssistant:"

        print("Running Qwen...")

        response = qwen_llm.invoke(prompt)
        trace(state, f"node=call_qwen completed (response_len={len(response)})")
        return {"qwen_response": response}

    # =========================================================================
    # NODE 5: print_both_responses
    # =========================================================================
    # This node reads both model responses from state and prints them to stdout.
    # State changes:
    #   - No changes (this node only reads state, doesn't modify it)
    def print_both_responses(state: AgentState) -> dict:
        """
        Node that prints both models' responses to stdout.

        Reads state:
            - llama_response: Llama output
            - qwen_response: Qwen output
        Updates state:
            - Nothing (returns empty dict, state unchanged)
        """
        trace(
            state,
            "node=print_both_responses entered "
            f"(llama_len={len(state.get('llama_response', ''))}, "
            f"qwen_len={len(state.get('qwen_response', ''))})",
        )

        print("\n" + "-" * 50)
        print("Llama Response:")
        print("-" * 50)
        print(state.get("llama_response", ""))

        print("\n" + "-" * 50)
        print("Qwen Response:")
        print("-" * 50)
        print(state.get("qwen_response", ""))

        # Return empty dict - no state updates from this node
        return {}

    # =========================================================================
    # ROUTING FUNCTION
    # =========================================================================
    # This function examines the state and determines which node to go to next.
    # It's used for conditional edges after get_user_input.
    # Three possible routes:
    #   1. User wants to quit -> END
    #   2. User entered a command/empty input -> reprompt (self-loop)
    #   3. User entered non-empty normal input -> proceed to fan_out_input
    def route_after_input(state: AgentState) -> str:
        """
        Routing function that determines the next node based on state.

        Examines state:
            - should_exit: If True, terminate the graph

        Returns:
            - "__end__": If user wants to quit
            - "get_user_input": If user entered command or empty input
            - "fan_out_input": If user provided non-empty normal input
        """
        trace(
            state,
            "route_after_input "
            f"(should_exit={state.get('should_exit')}, skip_llm={state.get('skip_llm')})",
        )

        # Check if user wants to exit
        if state.get("should_exit", False):
            return END

        # Commands and empty input should skip the LLM call.
        if state.get("skip_llm", False):
            return "get_user_input"

        # Default: Proceed to the fan-out node for non-empty, non-command input.
        return "fan_out_input"

    # =========================================================================
    # GRAPH CONSTRUCTION
    # =========================================================================
    # Create a StateGraph with our defined state structure
    graph_builder = StateGraph(AgentState)

    # Add nodes to the graph
    graph_builder.add_node("get_user_input", get_user_input)
    graph_builder.add_node("fan_out_input", fan_out_input)
    graph_builder.add_node("call_llama", call_llama)
    graph_builder.add_node("call_qwen", call_qwen)
    graph_builder.add_node("print_both_responses", print_both_responses)

    # Define edges:
    # 1. START -> get_user_input (always start by getting user input)
    graph_builder.add_edge(START, "get_user_input")

    # 2. get_user_input -> [conditional] -> fan_out_input/get_user_input/END
    #    Uses route_after_input to decide based on state.should_exit
    graph_builder.add_conditional_edges(
        "get_user_input",      # Source node
        route_after_input,      # Routing function that examines state
        {
            "get_user_input": "get_user_input",  # Command inputs loop to next prompt
            "fan_out_input": "fan_out_input",  # Normal input -> run both models
            END: END                  # Quit command -> terminate graph
        }
    )

    # 3. Fan out to both model calls in parallel
    graph_builder.add_edge("fan_out_input", "call_llama")
    graph_builder.add_edge("fan_out_input", "call_qwen")

    # 4. Join both model branches into a single print node
    graph_builder.add_edge("call_llama", "print_both_responses")
    graph_builder.add_edge("call_qwen", "print_both_responses")

    # 5. Loop back for next input
    graph_builder.add_edge("print_both_responses", "get_user_input")

    # Compile the graph into an executable form
    graph = graph_builder.compile()

    return graph

def save_graph_image(graph, filename="lg_graph.png"):
    """
    Generate a Mermaid diagram of the graph and save it as a PNG image.
    Uses the graph's built-in Mermaid export functionality.
    """
    try:
        # Get the Mermaid PNG representation of the graph
        # This requires the 'grandalf' package for rendering
        png_data = graph.get_graph(xray=True).draw_mermaid_png()

        # Write the PNG data to file
        with open(filename, "wb") as f:
            f.write(png_data)

        print(f"Graph image saved to {filename}")
    except Exception as e:
        print(f"Could not save graph image: {e}")
        print("You may need to install additional dependencies: pip install grandalf")

def main():
    """
    Main function that orchestrates the simple agent workflow:
    1. Initialize the LLM
    2. Create the LangGraph
    3. Save the graph visualization
    4. Run the graph once (it loops internally until user quits)

    The graph handles all looping internally through its edge structure:
    - get_user_input: Prompts and reads from stdin
    - call_llm: Processes input through the LLM
    - print_response: Outputs the response, then loops back to get_user_input

    The graph only terminates when the user types 'quit', 'exit', or 'q'.
    """
    print("=" * 50)
    print("LangGraph Simple Agent with Llama + Qwen")
    print("=" * 50)
    print()

    # Step 1: Create and configure both models
    device = get_device()
    llama_llm = create_model_llm("meta-llama/Llama-3.2-1B-Instruct", device)
    qwen_llm = create_model_llm("Qwen/Qwen2.5-0.5B-Instruct", device)

    # Step 2: Build the LangGraph with both models
    print("\nCreating LangGraph...")
    graph = create_graph(llama_llm, qwen_llm)
    print("Graph created successfully!")

    # Step 3: Save a visual representation of the graph before execution
    # This happens BEFORE any graph execution, showing the graph structure
    print("\nSaving graph visualization...")
    save_graph_image(graph)

    # Step 4: Run the graph - it will loop internally until user quits
    # Create initial state with empty/default values
    # The graph will loop continuously, updating state as it goes:
    #   - get_user_input displays banner, populates user_input and should_exit
    #   - parallel model nodes populate llama_response and qwen_response
    #   - print_both_responses displays output, then loops back to get_user_input
    initial_state: AgentState = {
        "user_input": "",
        "should_exit": False,
        "skip_llm": False,
        "trace_enabled": False,
        "llama_response": "",
        "qwen_response": ""
    }

    # Single invocation - the graph loops internally via print_response -> get_user_input
    # The graph only exits when route_after_input returns END (user typed quit/exit/q)
    graph.invoke(initial_state)

# Entry point - only run main() if this script is executed directly
if __name__ == "__main__":
    main()
