---
config:
  flowchart:
    curve: linear
---
graph TD;
	__start__([<p>__start__</p>]):::first
	get_user_input(get_user_input)
	call_model(call_model)
	run_tools(run_tools)
	print_response(print_response)
	__end__([<p>__end__</p>]):::last
	__start__ --> get_user_input;
	call_model -.-> print_response;
	call_model -.-> run_tools;
	get_user_input -.-> __end__;
	get_user_input -.-> call_model;
	print_response --> get_user_input;
	run_tools --> call_model;
	get_user_input -.-> get_user_input;
	classDef default fill:#f2f0ff,line-height:1.2
	classDef first fill-opacity:0
	classDef last fill:#bfb6fc
